language: perl
perl:
  - "5.8"
  - "5.8-thr"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20-thr"
  - "blead"
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
