language: perl
perl:
  - "5.10.0"
  - "5.10.0-thr"
  - "5.10.1"
  - "5.10.1-thr"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.20.1-thr"
  - "5.22"
  - "5.22.0-thr"
  - "dev"
matrix:
  include:
    - perl: 5.22
      env: COVERAGE=1
sudo: false
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
notifications:
  slack:
    rooms:
      - perl-test2:kI7LQjG4iRjIqA2JTl770A5F#general
    on_success: change
